name = "QuickHeaps"
uuid = "30b38841-0f52-47f8-a5f8-18d5d4064379"
authors = ["Éric Thiébaut <eric.thiebaut@univ-lyon1.fr>"]
version = "0.2.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
TypeUtils = "c3b1956e-8857-4d84-9b79-890df85b1e67"

[compat]
DataStructures = "0.18"
TypeUtils = "0.1, 0.2, 0.3"
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
